# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Time Nomad
email: hi.seqfx@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Time Nomad is a FREE astrology chart app for iPhone and iPad. 
  Charts for any location, natal charts, transits, synastry, progressions. 
  Planetary hours calculator and alarm. 
  Supports both tropical and sidereal Zodiac. 
  Analysis of future events for prediction techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://timenomad.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AstroTimeNomad
github_username: 

# Author, used by jekyll-feed
author: Time Nomad

# For SEO tag plugin
# https://github.com/jekyll/jekyll-seo-tag/
twitter:
  username: AstroTimeNomad
  card: summary_large_image

# Settings
show_excerpts: true

# Time Nomad collections directory
collections_dir: collections

# Time Nomad collections 
# Each collection can be
# reached via {{ site.my_collection }}
collections:
  documentation:
    output: true
    defaults:
      - scope:
          path: ""
          type: documentation
        values:
          layout: page
  news:
    output: true
    defaults:
      - scope:
          path: ""
          type: news
        values:
          layout: page
  newsletters:
    output: true
    defaults:
      - scope:
          path: ""
          type: newsletter
        values:
          layout: appfeed
  appfeed:
    output: true
    defaults:
      - scope:
          path: ""
          type: appfeed
        values:
          layout: appfeed

# Time Nomad global variables
# Reach via {{ site.my_app_... }}
my_app_store_name: time-nomad/id1092841332?mt=8
my_forum_url: https://www.reddit.com/r/TimeNomad/

# Staticman commenting engine
staticman: 
  username: astrotime
  repository: timenomad_app
  branch: master

# Google Analytics
google_analytics: UA-125404162-1

# Structured Data
structured_data:
  author: 
    name: Denis Zubkov
  publisher: 
    name: Time Nomad
    logo: 
      url: /images/time-nomad-logo-60x600.png
      width: 600
      height: 60
  softwareApplication:
    operatingSystem: Requires iOS 9.0 or later. Compatible with iPhone, iPad, and iPod touch.
    applicationCategory: Lifestyle
    offers:
      category: free
      price: 0
      priceCurrency: USD

# Build settings
future: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Plugins documentation:
# https://github.com/jekyll/jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
